# -*- coding: utf-8 -*-
""".ipye vishalini.p

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ti9LMVSeyZ9i1DTNLsKu4YiCmRzYdHG8
"""



n="abinaya kumar"
print(n.upper())
print(n.lower())
print(n.capitalize())
print(n.title())
print(n.swapcase())

n="abinaya kumar"
n[0:3]
n[-3:-1]
n[::2]
n[::-1]

n="vishalini"
print(n.center(30))
print(n.ljust(30))
print(n.rjust(30))
print("".zfill(4))

n="vishalini"
print(n.strip())
print(n.lstrip())
print(n.strip())

n="vishalini"
print(n.split())
m="vishalini"
print(m.split("k"))
p=""
print(p.join(["hi,hello"]))
s="vishalini"
print(s.rsplit("a"))
print("hi guys".partition(" "))

n="abinaya kumar"
print(n.find("i"))
print(n.find("a"))
print(n.rfind("a"))
print(n.index("y"))
print(n.count("a"))
print(n.replace("a","$"))
print(n.startswith("a"))
print(n.endswith("r"))

